# Generated by Django 4.1.7 on 2023-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField()),
                ('V1', models.IntegerField()),
                ('V2', models.IntegerField()),
                ('V3', models.IntegerField()),
                ('V4', models.IntegerField()),
                ('V5', models.IntegerField()),
                ('V6', models.IntegerField()),
                ('V7', models.IntegerField()),
                ('V8', models.IntegerField()),
                ('V9', models.IntegerField()),
                ('V10', models.IntegerField()),
                ('V12', models.IntegerField()),
                ('V13', models.IntegerField()),
                ('V14', models.IntegerField()),
                ('V15', models.IntegerField()),
                ('V16', models.IntegerField()),
                ('V17', models.IntegerField()),
                ('V18', models.IntegerField()),
                ('V19', models.IntegerField()),
                ('V20', models.IntegerField()),
                ('V21', models.IntegerField()),
                ('V22', models.IntegerField()),
                ('V23', models.IntegerField()),
                ('V24', models.IntegerField()),
                ('V25', models.IntegerField()),
                ('V26', models.IntegerField()),
                ('V27', models.IntegerField()),
                ('V28', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Class', models.CharField(max_length=5)),
            ],
        ),
    ]
